// File generato automaticamente — foto scaricate dai cataloghi ufficiali dei brand.
export const CATALOGO_EXTRA = {
 gbgroupSilk: [
  { src: '/images/vendor-photos/gbgroup/silk-01.jpg', title: 'GB Group Silk — 1' },
  { src: '/images/vendor-photos/gbgroup/silk-02.jpg', title: 'GB Group Silk — 2' },
  { src: '/images/vendor-photos/gbgroup/silk-03.jpg', title: 'GB Group Silk — 3' },
  { src: '/images/vendor-photos/gbgroup/silk-04.jpg', title: 'GB Group Silk — 4' },
  { src: '/images/vendor-photos/gbgroup/silk-05.jpg', title: 'GB Group Silk — 5' },
  { src: '/images/vendor-photos/gbgroup/silk-06.jpg', title: 'GB Group Silk — 6' },
  { src: '/images/vendor-photos/gbgroup/silk-07.jpg', title: 'GB Group Silk — 7' },
  { src: '/images/vendor-photos/gbgroup/silk-08.jpg', title: 'GB Group Silk — 8' },
 ],
 gbgroupExtreme: [
  { src: '/images/vendor-photos/gbgroup/extreme-01.jpg', title: 'GB Group Extreme — 1' },
  { src: '/images/vendor-photos/gbgroup/extreme-02.jpg', title: 'GB Group Extreme — 2' },
  { src: '/images/vendor-photos/gbgroup/extreme-03.jpg', title: 'GB Group Extreme — 3' },
  { src: '/images/vendor-photos/gbgroup/extreme-04.jpg', title: 'GB Group Extreme — 4' },
  { src: '/images/vendor-photos/gbgroup/extreme-05.jpg', title: 'GB Group Extreme — 5' },
  { src: '/images/vendor-photos/gbgroup/extreme-06.jpg', title: 'GB Group Extreme — 6' },
  { src: '/images/vendor-photos/gbgroup/extreme-07.jpg', title: 'GB Group Extreme — 7' },
  { src: '/images/vendor-photos/gbgroup/extreme-08.jpg', title: 'GB Group Extreme — 8' },
  { src: '/images/vendor-photos/gbgroup/extreme-09.jpg', title: 'GB Group Extreme — 9' },
 ],
 gbgroupMoon: [
  { src: '/images/vendor-photos/gbgroup/moon-01.jpg', title: 'GB Group Moon — 1' },
  { src: '/images/vendor-photos/gbgroup/moon-02.jpg', title: 'GB Group Moon — 2' },
  { src: '/images/vendor-photos/gbgroup/moon-04.jpg', title: 'GB Group Moon — 3' },
  { src: '/images/vendor-photos/gbgroup/moon-05.jpg', title: 'GB Group Moon — 4' },
  { src: '/images/vendor-photos/gbgroup/moon-08.jpg', title: 'GB Group Moon — 5' },
  { src: '/images/vendor-photos/gbgroup/moon-09.jpg', title: 'GB Group Moon — 6' },
  { src: '/images/vendor-photos/gbgroup/moon-11.jpg', title: 'GB Group Moon — 7' },
  { src: '/images/vendor-photos/gbgroup/moon-12.jpg', title: 'GB Group Moon — 8' },
 ],
 gbgroupCompact: [
  { src: '/images/vendor-photos/gbgroup/compact-01.jpg', title: 'GB Group Compact — 1' },
  { src: '/images/vendor-photos/gbgroup/compact-02.jpg', title: 'GB Group Compact — 2' },
  { src: '/images/vendor-photos/gbgroup/compact-03.jpg', title: 'GB Group Compact — 3' },
  { src: '/images/vendor-photos/gbgroup/compact-04.jpg', title: 'GB Group Compact — 4' },
  { src: '/images/vendor-photos/gbgroup/compact-05.jpg', title: 'GB Group Compact — 5' },
  { src: '/images/vendor-photos/gbgroup/compact-06.jpg', title: 'GB Group Compact — 6' },
  { src: '/images/vendor-photos/gbgroup/compact-07.jpg', title: 'GB Group Compact — 7' },
 ],
 gbgroupUnderground: [
  { src: '/images/vendor-photos/gbgroup/underground-01.jpg', title: 'GB Group Underground — 1' },
  { src: '/images/vendor-photos/gbgroup/underground-02.jpg', title: 'GB Group Underground — 2' },
  { src: '/images/vendor-photos/gbgroup/underground-03.jpg', title: 'GB Group Underground — 3' },
  { src: '/images/vendor-photos/gbgroup/underground-04.jpg', title: 'GB Group Underground — 4' },
  { src: '/images/vendor-photos/gbgroup/underground-05.jpg', title: 'GB Group Underground — 5' },
  { src: '/images/vendor-photos/gbgroup/underground-06.jpg', title: 'GB Group Underground — 6' },
  { src: '/images/vendor-photos/gbgroup/underground-07.jpg', title: 'GB Group Underground — 7' },
  { src: '/images/vendor-photos/gbgroup/underground-08.jpg', title: 'GB Group Underground — 8' },
  { src: '/images/vendor-photos/gbgroup/underground-09.jpg', title: 'GB Group Underground — 9' },
  { src: '/images/vendor-photos/gbgroup/underground-10.jpg', title: 'GB Group Underground — 10' },
 ],
 gbgroupOnda: [
  { src: '/images/vendor-photos/gbgroup/onda-02.jpg', title: 'GB Group Onda — 1' },
  { src: '/images/vendor-photos/gbgroup/onda-03.jpg', title: 'GB Group Onda — 2' },
  { src: '/images/vendor-photos/gbgroup/onda-04.jpg', title: 'GB Group Onda — 3' },
  { src: '/images/vendor-photos/gbgroup/onda-05.jpg', title: 'GB Group Onda — 4' },
  { src: '/images/vendor-photos/gbgroup/onda-06.jpg', title: 'GB Group Onda — 5' },
  { src: '/images/vendor-photos/gbgroup/onda-07.jpg', title: 'GB Group Onda — 6' },
  { src: '/images/vendor-photos/gbgroup/onda-08.jpg', title: 'GB Group Onda — 7' },
 ],
 savoia: [
  { src: '/images/vendor-photos/savoia/antichi-decori.jpg', title: 'Ceramiche Savoia — 1' },
  { src: '/images/vendor-photos/savoia/bicottura.jpg', title: 'Ceramiche Savoia — 2' },
  { src: '/images/vendor-photos/savoia/cementi-img-01.jpg', title: 'Ceramiche Savoia — 3' },
  { src: '/images/vendor-photos/savoia/cementi-img-02.jpg', title: 'Ceramiche Savoia — 4' },
  { src: '/images/vendor-photos/savoia/cementi-img-03.jpg', title: 'Ceramiche Savoia — 5' },
  { src: '/images/vendor-photos/savoia/cementi-img-04.jpg', title: 'Ceramiche Savoia — 6' },
  { src: '/images/vendor-photos/savoia/cementi-img-05.jpg', title: 'Ceramiche Savoia — 7' },
  { src: '/images/vendor-photos/savoia/cementi-img-06.jpg', title: 'Ceramiche Savoia — 8' },
  { src: '/images/vendor-photos/savoia/cementi.jpg', title: 'Ceramiche Savoia — 9' },
  { src: '/images/vendor-photos/savoia/decori-img-01.jpg', title: 'Ceramiche Savoia — 10' },
  { src: '/images/vendor-photos/savoia/decori-img-02.jpg', title: 'Ceramiche Savoia — 11' },
  { src: '/images/vendor-photos/savoia/decori-img-03.jpg', title: 'Ceramiche Savoia — 12' },
  { src: '/images/vendor-photos/savoia/decori-img-04.jpg', title: 'Ceramiche Savoia — 13' },
  { src: '/images/vendor-photos/savoia/decori-img-05.jpg', title: 'Ceramiche Savoia — 14' },
  { src: '/images/vendor-photos/savoia/decori-img-06.jpg', title: 'Ceramiche Savoia — 15' },
  { src: '/images/vendor-photos/savoia/decori-img-07.jpg', title: 'Ceramiche Savoia — 16' },
  { src: '/images/vendor-photos/savoia/distintive.jpg', title: 'Ceramiche Savoia — 17' },
  { src: '/images/vendor-photos/savoia/legni-img-01.jpg', title: 'Ceramiche Savoia — 18' },
  { src: '/images/vendor-photos/savoia/legni-img-02.jpg', title: 'Ceramiche Savoia — 19' },
  { src: '/images/vendor-photos/savoia/legni-img-03.jpg', title: 'Ceramiche Savoia — 20' },
  { src: '/images/vendor-photos/savoia/legni-img-04.jpg', title: 'Ceramiche Savoia — 21' },
  { src: '/images/vendor-photos/savoia/legni-img-05.jpg', title: 'Ceramiche Savoia — 22' },
  { src: '/images/vendor-photos/savoia/legni.jpg', title: 'Ceramiche Savoia — 23' },
  { src: '/images/vendor-photos/savoia/pietre-img-01.jpg', title: 'Ceramiche Savoia — 24' },
  { src: '/images/vendor-photos/savoia/pietre-img-02.jpg', title: 'Ceramiche Savoia — 25' },
  { src: '/images/vendor-photos/savoia/pietre-img-03.jpg', title: 'Ceramiche Savoia — 26' },
  { src: '/images/vendor-photos/savoia/pietre-img-04.jpg', title: 'Ceramiche Savoia — 27' },
  { src: '/images/vendor-photos/savoia/pietre-img-05.jpg', title: 'Ceramiche Savoia — 28' },
  { src: '/images/vendor-photos/savoia/pietre-img-06.jpg', title: 'Ceramiche Savoia — 29' },
  { src: '/images/vendor-photos/savoia/pietre-img-07.jpg', title: 'Ceramiche Savoia — 30' },
  { src: '/images/vendor-photos/savoia/pietre-img-08.jpg', title: 'Ceramiche Savoia — 31' },
  { src: '/images/vendor-photos/savoia/pietre-img-09.jpg', title: 'Ceramiche Savoia — 32' },
  { src: '/images/vendor-photos/savoia/pietre-img-10.jpg', title: 'Ceramiche Savoia — 33' },
  { src: '/images/vendor-photos/savoia/pietre-img-11.jpg', title: 'Ceramiche Savoia — 34' },
  { src: '/images/vendor-photos/savoia/pietre-img-12.jpg', title: 'Ceramiche Savoia — 35' },
  { src: '/images/vendor-photos/savoia/pietre-img-13.jpg', title: 'Ceramiche Savoia — 36' },
  { src: '/images/vendor-photos/savoia/pietre-img-14.jpg', title: 'Ceramiche Savoia — 37' },
  { src: '/images/vendor-photos/savoia/pietre.jpg', title: 'Ceramiche Savoia — 38' },
 ],
 catalano: [
  { src: '/images/vendor-photos/catalano/alvea-01.webp', title: 'Catalano Alvea — 1' },
  { src: '/images/vendor-photos/catalano/alvea-02.webp', title: 'Catalano Alvea — 2' },
  { src: '/images/vendor-photos/catalano/alvea-03.webp', title: 'Catalano Alvea — 3' },
  { src: '/images/vendor-photos/catalano/alvea-04.webp', title: 'Catalano Alvea — 4' },
  { src: '/images/vendor-photos/catalano/alvea-05.webp', title: 'Catalano Alvea — 5' },
  { src: '/images/vendor-photos/catalano/alvea-06.webp', title: 'Catalano Alvea — 6' },
  { src: '/images/vendor-photos/catalano/alvea-07.webp', title: 'Catalano Alvea — 7' },
  { src: '/images/vendor-photos/catalano/alvea-08.webp', title: 'Catalano Alvea — 8' },
  { src: '/images/vendor-photos/catalano/alvea-09.webp', title: 'Catalano Alvea — 9' },
 ],
 opera: [
  { src: '/images/vendor-photos/opera/colors.jpg', title: 'Opera Sanitari — 1' },
  { src: '/images/vendor-photos/opera/lavabi-arredo.jpg', title: 'Opera Sanitari — 2' },
  { src: '/images/vendor-photos/opera/piatti-doccia.jpg', title: 'Opera Sanitari — 3' },
  { src: '/images/vendor-photos/opera/piatti-marmoresina.jpg', title: 'Opera Sanitari — 4' },
  { src: '/images/vendor-photos/opera/zero.jpg', title: 'Opera Sanitari — 5' },
 ],
 galassia: [
  { src: '/images/vendor-photos/galassia/core.jpg', title: 'Galassia — 1' },
  { src: '/images/vendor-photos/galassia/slide-1.jpg', title: 'Galassia — 2' },
  { src: '/images/vendor-photos/galassia/slide-10.jpg', title: 'Galassia — 3' },
  { src: '/images/vendor-photos/galassia/slide-11.jpg', title: 'Galassia — 4' },
  { src: '/images/vendor-photos/galassia/slide-12.jpg', title: 'Galassia — 5' },
  { src: '/images/vendor-photos/galassia/slide-13.jpg', title: 'Galassia — 6' },
  { src: '/images/vendor-photos/galassia/slide-2.jpg', title: 'Galassia — 7' },
  { src: '/images/vendor-photos/galassia/slide-3.jpg', title: 'Galassia — 8' },
  { src: '/images/vendor-photos/galassia/slide-4.jpg', title: 'Galassia — 9' },
  { src: '/images/vendor-photos/galassia/slide-5.jpg', title: 'Galassia — 10' },
  { src: '/images/vendor-photos/galassia/slide-6.jpg', title: 'Galassia — 11' },
  { src: '/images/vendor-photos/galassia/slide-7.jpg', title: 'Galassia — 12' },
  { src: '/images/vendor-photos/galassia/slide-8.jpg', title: 'Galassia — 13' },
  { src: '/images/vendor-photos/galassia/slide-9.jpg', title: 'Galassia — 14' },
 ],
 karag: [
  { src: '/images/vendor-photos/karag/milos-01.jpg', title: 'Karag Milos — 1' },
 ],
 wcBidetAmbient: [
  { src: '/images/vendor-photos/wc-bidet-ambient/catalano-amb-01.webp', title: 'WC e Bidet — 1' },
  { src: '/images/vendor-photos/wc-bidet-ambient/catalano-amb-02.webp', title: 'WC e Bidet — 2' },
  { src: '/images/vendor-photos/wc-bidet-ambient/catalano-amb-03.webp', title: 'WC e Bidet — 3' },
  { src: '/images/vendor-photos/wc-bidet-ambient/opera-amb-01.jpg', title: 'WC e Bidet — 1' },
 ],
} as const;
